name: AuthPipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches: [ main ]

jobs:
  # -----------------------------
  # Stage 1: Build & Test
  # -----------------------------
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build & Run Tests
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
          TOKEN_EXPIRATION_IN_MINUTES: ${{ secrets.TOKEN_EXPIRATION_IN_MINUTES }}
          REFRESH_TOKEN_EXPIRATION_IN_DAYS: ${{ secrets.REFRESH_TOKEN_EXPIRATION_IN_DAYS }}
        run: ./mvnw clean verify

  # -----------------------------
  # Stage 2: Docker Build
  # -----------------------------
  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            docker build --target production -t spring-auth-server:prod .
          else
            docker build --target development -t spring-auth-server:dev .
          fi
          
    # -----------------------------
  # Stage 3: Deploy
  # -----------------------------
#  deploy:
#    runs-on: ubuntu-latest
#    needs: docker-build
#    steps:
#      - name: Deploy to Server
#        uses: appleboy/ssh-action@v0.1.8
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          script: |
#            # Choose image based on branch
#            if [ "${GITHUB_REF_NAME}" = "main" ]; then
#              IMAGE=spring-auth-server:prod
#              ENV_FILE=.env.prod
#            else
#              IMAGE=spring-auth-server:dev
#              ENV_FILE=.env.dev
#            fi
#




