name: AuthPipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches: [ main ]

jobs:
  # -----------------------------
  # Stage 1: Build & Test
  # -----------------------------
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build & Run Tests
        run: ./mvnw clean verify



  # -----------------------------
  # Stage 2: Docker Build & Push to Docker Hub
  # -----------------------------

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          # Determine branch type
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            IMAGE_TAG=latest
            TARGET=production
          else
            IMAGE_TAG=dev
            TARGET=development
          fi
          
          # Build Docker image
          docker build --target $TARGET -t ${{ secrets.DOCKERHUB_USERNAME }}/rbac-server:$IMAGE_TAG .
          
          # Push image to Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rbac-server:$IMAGE_TAG

    # -----------------------------
  # Stage 3: Deploy
  # -----------------------------
#  deploy:
#    runs-on: ubuntu-latest
#    needs: docker-build
#    steps:
#      - name: Deploy to Server
#        uses: appleboy/ssh-action@v0.1.8
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          script: |
#            # Choose image based on branch
#            if [ "${GITHUB_REF_NAME}" = "main" ]; then
#              IMAGE=spring-auth-server:prod
#              ENV_FILE=.env.prod
#            else
#              IMAGE=spring-auth-server:dev
#              ENV_FILE=.env.dev
#            fi
#




